---
meta:
  # fly -t ohio-cf login -c https://ci2.starkandwayne.com -n cfcommunity
  target:  ohio-cf
  url:     https://ci2.starkandwayne.com

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  github:
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  aws:
    access_key: ((aws-cfcommunity-access))
    secret_key: ((aws-cfcommunity-secret))

  bosh:
    # target:   ((bosh_environment))
    # cacert:   ((bosh_ca_cert))
    # username: ((bosh_client))
    # password: ((bosh_client_secret))
    # stemcell_cpi: aws-xen-hvm
    target:   ((bosh-lite-environment))
    cacert:   ((bosh-lite-ca-cert))
    username: ((bosh-lite-client))
    password: ((bosh-lite-client-secret))
